language: nix

os:
  - linux

before_script:
  - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
  - mkdir -p ~/.config/nixpkgs
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix authtoken $AUTHTOKEN

env:
  - NIXPKGS=19.03
  - NIXPKGS=unstable

script:
  - nix run -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-$NIXPKGS.tar.gz nixpkgs.haskellPackages.hlint -c hlint src
  - nix build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-$NIXPKGS.tar.gz -f ./release.nix imageservice -o result-imageservice
  - nix build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-$NIXPKGS.tar.gz -f ./frontend frontend -o result-frontend
  - readlink result-imageservice | cachix push masser-ebook-manager
  - readlink result-frontend | cachix push masser-ebook-manager
