name: "Test"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: masser-ebook-manager
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # - run: nix run nixpkgs.hlint -c hlint .
    - run: nix build -f release.nix -I nixpkgs=channel:nixos-20.03
    - run: nix-shell -I nixpkgs=channel:nixos-20.03 --run 'echo OK'
    # - run: nix-shell ./shell.nix --run './restyle.sh' && git diff --exit-code
