name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/cachix-action@v12
      with:
        name: masser-ebook-manager
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # - run: nix run nixpkgs.hlint -c hlint .
    - run: nix build -f release.nix -I nixpkgs=channel:nixos-20.03 -A imageservice
    - run: nix-shell -I nixpkgs=channel:nixos-20.03 --run 'echo OK'
    # - run: nix-shell ./shell.nix --run './restyle.sh' && git diff --exit-code
